In [1]:
import pandas as pd
import numpy as np
import os
import schedule
import time
import calendar
import datetime as dt
import logging
import sys
from datetime import datetime, timedelta
from mlxtend.frequent_patterns import association_rules
from sqlalchemy import create_engine, text
from mlxtend.preprocessing import TransactionEncoder
from fpgrowth_py import fpgrowth
from itertools import combinations

In [12]:
db_user = os.environ.get('dbwh_8555_user')
db_pass = os.environ.get('dbwh_8555_pass')

connection_string = f"mssql+pyodbc://{db_user}:{db_pass}@192.168.85.55/DBWH_8555?driver=ODBC+Driver+17+for+SQL+Server"
engine = create_engine(connection_string)

query = text(
    """
    SELECT 
        dd.[date] AS TRX_date,
        [StoreCode],
        [BillNo],
        [ItemCode],
        ITEMLONGNAME,
        [Quantity],
        DEPARTMENT,
        CLASS,
        SUBCLASS,
        [UOM_CD],
        [TotalAmt],
        [NetValue],
        [WACValue],
        [CSM_QTY],
        [CONSIGN_FINAL_QTY],
        [POS_FINAL_QTY]
    FROM [DBWH_8555].[dbo].[FactSalesTrxNew] fstn
    INNER JOIN dimdate dd ON dd.datekey = fstn.DateKey
    INNER JOIN DimItem di ON fstn.ItemCode = di.ITMCD
    WHERE dd.[date] BETWEEN :start_date AND :end_date AND StoreCode = '083'
    """)

In [45]:
with engine.connect() as conn:
    start_date = '2025-11-01'
    end_date = '2025-11-30'

    store_df = pd.read_sql(query, conn,  params={'start_date': start_date, 'end_date': end_date})


transactions = (
    store_df.groupby("BillNo")["ItemCode"]
    .apply(lambda x: list(set(x)))  # remove duplicates
    .apply(list).tolist()
)
n_transactions = len(transactions)

n_transactions

48

In [46]:
print("Total transactions:", len(transactions))

unique_items = set(item for t in transactions for item in t)
print("Unique products:", len(unique_items))

max_items_per_bill = max(len(t) for t in transactions)
print("Max items per transaction:", max_items_per_bill)

avg_items = sum(len(t) for t in transactions) / len(transactions)
print("Average items per transaction:", avg_items)

Total transactions: 48
Unique products: 51
Max items per transaction: 14
Average items per transaction: 5.541666666666667

In [47]:
#transactions.to_csv('transaction_test.csv', index=False)
transactions

[['101002078907'],
 ['101024032325',
  '101024011780',
  '101023011643',
  '101023011348',
  '101051022861',
  '101024034834',
  '101024060197',
  '101024011712'],
 ['101023011375',
  '101007001685',
  '101024011780',
  '101023011348',
  '101051022861'],
 ['101043020196', '101007001685', '101051022861', '101024011746'],
 ['101003004904',
  '101013065724',
  '101011040533',
  '101051022861',
  '101003041660'],
 ['101003059878',
  '101024011743',
  '101003007810',
  '101007001685',
  '101024011748',
  '101024011780',
  '101006073899',
  '101023011643',
  '101024026542',
  '101024011746',
  '101003007811',
  '101003007812',
  '101003005360',
  '101024011712'],
 ['101024032325',
  '101023011375',
  '101023011643',
  '101023011348',
  '101051022861',
  '101024011743',
  '101024011712'],
 ['101024026542', '101024011797'],
 ['101024032325', '101024026542', '101024011797'],
 ['101010000873', '101003004904', '101003041660', '101051072903'],
 ['101002005378',
  '101011077430',
  '101003007810',
  '101023011375',
  '101023011348',
  '101006049321',
  '101003005360'],
 ['101051022861'],
 ['101024032325', '101011040533', '101011077436', '101024011712'],
 ['101024011797'],
 ['101024011797',
  '101024011683',
  '101023011348',
  '101051022861',
  '101024011712'],
 ['101024011797',
  '101024032325',
  '101007001685',
  '101023011348',
  '101003041660'],
 ['101024011797',
  '101024011766',
  '101024032325',
  '101051022866',
  '101023011375',
  '101023011348',
  '101024026542'],
 ['101002005378', '101003059878', '101003004904', '101006049321'],
 ['101002005378',
  '101003004904',
  '101024011748',
  '101023011348',
  '101011040533',
  '101051022861'],
 ['101033016209', '101002005378', '101051022861', '101003004904'],
 ['101024011766',
  '101007001685',
  '101023011534',
  '101023011348',
  '101024026542',
  '101051022861'],
 ['101002005378',
  '101003059878',
  '101051022866',
  '101023011375',
  '101006073899',
  '101023011348',
  '101007049264',
  '101024034834',
  '101051022861',
  '101003007811',
  '101005061437',
  '101006049321'],
 ['101002005378',
  '101010000816',
  '101013065724',
  '101023011348',
  '101011040533',
  '101024026542',
  '101003041660',
  '101024011746',
  '101024034834',
  '101024011743',
  '101051022861',
  '101005061437'],
 ['101002005378',
  '101024011797',
  '101024011743',
  '101024032325',
  '101051022866',
  '101023011375',
  '101013065724',
  '101023011348',
  '101011040533',
  '101024026542',
  '101003041660',
  '101003007811',
  '101003007812',
  '101024011712'],
 ['101024032325'],
 ['101024011736', '101024011746'],
 ['101024032325', '101051022866', '101024026542'],
 ['101002005378',
  '101003004904',
  '101010000873',
  '101051022866',
  '101003007810',
  '101013065724',
  '101023011348',
  '101011040533',
  '101003041660',
  '101003007811',
  '101003005360',
  '101024011712'],
 ['101002005378',
  '101023011375',
  '101007001685',
  '101023011643',
  '101023011348',
  '101024026542',
  '101024011712'],
 ['101002005378', '101023011375', '101024026542', '101006049321'],
 ['101024032325', '101023011348', '101024011797', '101006049321'],
 ['101023011375',
  '101007001685',
  '101024011736',
  '101024011769',
  '101023011643',
  '101023011348',
  '101011040533',
  '101023011591',
  '101024011743',
  '101006049321',
  '101024011712'],
 ['101011040533', '101051022861'],
 ['101024011797',
  '101024011766',
  '101024032325',
  '101024011683',
  '101024011780',
  '101051022866',
  '101024026542',
  '101024011743',
  '101005061435',
  '101024011712'],
 ['101024032325', '101051022861', '101024011797', '101024011766'],
 ['101003004904',
  '101024011797',
  '101024032325',
  '101051022866',
  '101024026542',
  '101003041660',
  '101024011743',
  '101002008401',
  '101043046887',
  '101024011712'],
 ['101024011743', '101024026542', '101024011797', '101024011766'],
 ['101002005378', '101003072747', '101003041660', '101006073899'],
 ['101003004904', '101003041660'],
 ['101002005378',
  '101023011375',
  '101007001685',
  '101023011348',
  '101051022861',
  '101003041660',
  '101006049321'],
 ['101024011797',
  '101024011766',
  '101007001685',
  '101024026542',
  '101023011591',
  '101006049321'],
 ['101023011595',
  '101024032325',
  '101024011683',
  '101013009719',
  '101013009720'],
 ['101024011766',
  '101024032325',
  '101051022861',
  '101024011743',
  '101024011712'],
 ['101024011797',
  '101024032325',
  '101051022861',
  '101024011743',
  '101024060197',
  '101024011712'],
 ['101003004904', '101003041660', '101024011712'],
 ['101002005378'],
 ['101002005378',
  '101003004904',
  '101003059878',
  '101003041660',
  '101003007811',
  '101003005360'],
 ['101003004904',
  '101023011375',
  '101023011348',
  '101011040533',
  '101051022861',
  '101003041660']]

In [48]:
freqItemSet, rules_fpg = fpgrowth(transactions, minSupRatio=0.1, minConf=0.5)
transactions_sets = [set(t) for t in transactions]  # convert once, reuse

In [59]:
freqItemSet

[{'101023011643'},
 {'101023011643', '101024011712'},
 {'101003007811'},
 {'101024011766'},
 {'101024011766', '101024026542'},
 {'101024011766', '101024011797'},
 {'101051022866'},
 {'101024026542', '101051022866'},
 {'101024032325', '101051022866'},
 {'101024026542', '101024032325', '101051022866'},
 {'101006049321'},
 {'101006049321', '101023011375'},
 {'101002005378', '101006049321'},
 {'101006049321', '101023011348'},
 {'101007001685'},
 {'101007001685', '101023011348'},
 {'101011040533'},
 {'101003041660', '101011040533'},
 {'101011040533', '101051022861'},
 {'101011040533', '101023011348'},
 {'101024011743'},
 {'101024011743', '101024011797'},
 {'101024011743', '101024026542'},
 {'101024011743', '101024032325'},
 {'101024011712', '101024011743', '101024032325'},
 {'101024011712', '101024011743'},
 {'101023011375'},
 {'101023011375', '101051022861'},
 {'101023011348', '101023011375', '101051022861'},
 {'101002005378', '101023011375'},
 {'101002005378', '101023011348', '101023011375'},
 {'101023011348', '101023011375'},
 {'101003004904'},
 {'101002005378', '101003004904'},
 {'101003004904', '101003041660'},
 {'101003041660'},
 {'101003041660', '101023011348'},
 {'101002005378', '101003041660'},
 {'101024011712'},
 {'101024011712', '101051022861'},
 {'101024011712', '101024026542'},
 {'101024011712', '101024011797'},
 {'101023011348', '101024011712'},
 {'101024011712', '101024032325'},
 {'101024026542'},
 {'101024011797', '101024026542'},
 {'101023011348', '101024026542'},
 {'101024026542', '101024032325'},
 {'101024011797'},
 {'101023011348', '101024011797'},
 {'101024011797', '101024032325'},
 {'101002005378'},
 {'101002005378', '101051022861'},
 {'101002005378', '101023011348'},
 {'101024032325'},
 {'101024032325', '101051022861'},
 {'101023011348', '101024032325'},
 {'101023011348'},
 {'101051022861'},
 {'101023011348', '101051022861'}]

In [58]:
rules_fpg

[[{'101023011643'}, {'101024011712'}, 1.0],
 [{'101024011766'}, {'101024026542'}, 0.7142857142857143],
 [{'101024011766'}, {'101024011797'}, 0.7142857142857143],
 [{'101051022866'}, {'101024026542'}, 0.7142857142857143],
 [{'101051022866'}, {'101024032325'}, 0.7142857142857143],
 [{'101051022866'}, {'101024026542', '101024032325'}, 0.7142857142857143],
 [{'101024032325', '101051022866'}, {'101024026542'}, 1.0],
 [{'101024026542', '101024032325'}, {'101051022866'}, 0.8333333333333334],
 [{'101024026542', '101051022866'}, {'101024032325'}, 1.0],
 [{'101006049321'}, {'101023011375'}, 0.625],
 [{'101006049321'}, {'101002005378'}, 0.625],
 [{'101006049321'}, {'101023011348'}, 0.625],
 [{'101007001685'}, {'101023011348'}, 0.6666666666666666],
 [{'101011040533'}, {'101003041660'}, 0.5555555555555556],
 [{'101011040533'}, {'101051022861'}, 0.5555555555555556],
 [{'101011040533'}, {'101023011348'}, 0.6666666666666666],
 [{'101024011743'}, {'101024026542'}, 0.6],
 [{'101024011743'}, {'101024032325'}, 0.6],
 [{'101024011743'}, {'101024011712', '101024032325'}, 0.6],
 [{'101024011743', '101024032325'}, {'101024011712'}, 1.0],
 [{'101024011712', '101024011743'}, {'101024032325'}, 0.75],
 [{'101024011712', '101024032325'}, {'101024011743'}, 0.75],
 [{'101024011743'}, {'101024011712'}, 0.8],
 [{'101024011712'}, {'101024011743'}, 0.5714285714285714],
 [{'101023011375', '101051022861'}, {'101023011348'}, 1.0],
 [{'101023011375'}, {'101002005378'}, 0.5454545454545454],
 [{'101002005378', '101023011375'}, {'101023011348'}, 0.8333333333333334],
 [{'101002005378', '101023011348'}, {'101023011375'}, 0.625],
 [{'101023011375'}, {'101023011348'}, 0.9090909090909091],
 [{'101023011348'}, {'101023011375'}, 0.5555555555555556],
 [{'101003004904'}, {'101003041660'}, 0.7272727272727273],
 [{'101003041660'}, {'101003004904'}, 0.6153846153846154],
 [{'101024011712'}, {'101024032325'}, 0.5714285714285714],
 [{'101024026542'}, {'101024011797'}, 0.5714285714285714],
 [{'101024011797'}, {'101024026542'}, 0.5714285714285714],
 [{'101024032325'}, {'101024011797'}, 0.5625],
 [{'101024011797'}, {'101024032325'}, 0.6428571428571429],
 [{'101002005378'}, {'101023011348'}, 0.5714285714285714],
 [{'101023011348'}, {'101051022861'}, 0.5555555555555556],
 [{'101051022861'}, {'101023011348'}, 0.5555555555555556]]

In [52]:
def calc_support(itemset):
    return sum(1 for t in transactions_sets if itemset.issubset(t)) / n_transactions

frequent_itemsets = pd.DataFrame([
    {"itemsets": frozenset(itemset), "support": calc_support(itemset)}
    for itemset in freqItemSet
])

In [56]:
frequent_itemsets.head(3)

                       itemsets   support
0                (101023011643)  0.104167
1  (101023011643, 101024011712)  0.104167
2                (101003007811)  0.104167

In [ ]:
# Ensure column dtypes
frequent_itemsets["itemsets"] = frequent_itemsets["itemsets"].apply(frozenset)
frequent_itemsets = frequent_itemsets.drop_duplicates(subset=["itemsets"]).reset_index(drop=True)

In [55]:
frequent_itemsets.head(3)

                       itemsets   support
0                (101023011643)  0.104167
1  (101023011643, 101024011712)  0.104167
2                (101003007811)  0.104167