In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from sqlalchemy import create_engine, text
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules, fpgrowth
from mlxtend.preprocessing import TransactionEncoder
from scipy.sparse import csr_matrix


from fpgrowth_py import fpgrowth
from itertools import combinations

In [4]:
db_user = os.environ.get('dbwh_8555_user')
db_pass = os.environ.get('dbwh_8555_pass')

connection_string = f"mssql+pyodbc://{db_user}:{db_pass}@192.168.85.55/DBWH_8555?driver=ODBC+Driver+17+for+SQL+Server"
engine = create_engine(connection_string)

query = text(
    """
    SELECT 
        dd.[date] AS TRX_date,
        [StoreCode],
        [BillNo],
        [ItemCode],
        ITEMLONGNAME,
        [Quantity],
        DEPARTMENT,
        CLASS,
        SUBCLASS,
        [UOM_CD],
        [TotalAmt],
        [NetValue],
        [WACValue],
        [CSM_QTY],
        [CONSIGN_FINAL_QTY],
        [POS_FINAL_QTY]
    FROM [DBWH_8555].[dbo].[FactSalesTrxNew] fstn
    INNER JOIN dimdate dd ON dd.datekey = fstn.DateKey
    INNER JOIN DimItem di ON fstn.ItemCode = di.ITMCD
    WHERE dd.[date] BETWEEN :start_date AND :end_date AND StoreCode = '083'
    """)

In [ ]:
with engine.connect() as conn:
    start_date = '2025-11-01'
    end_date = '2025-11-30'

    store_df = pd.read_sql(query, conn,  params={'start_date': start_date, 'end_date': end_date})


#df = pd.read_csv('t10_trx_data.csv')
    
store_df = df[~df['ITEMLONGNAME'].str.contains('pepito bag', case=False, na=False)]
#df['month_year'] = pd.to_datetime(df['month_year'], format='%m-%Y')
#df['rule'] = df['antecedents'] + " → " + df['consequents']

df.info()
df.head(1)

<class 'pandas.core.frame.DataFrame'>
Index: 290 entries, 0 to 289
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TRX_date           290 non-null    datetime64[ns]
 1   StoreCode          290 non-null    object
 2   BillNo             290 non-null    object
 3   ItemCode           290 non-null    object
 4   ITEMLONGNAME       290 non-null    object
 5   Quantity           290 non-null    float64
 6   DEPARTMENT         290 non-null    object
 7   CLASS              290 non-null    object
 8   SUBCLASS           290 non-null    object
 9   UOM_CD             290 non-null    object
 10  TotalAmt           290 non-null    float64
 11  NetValue           290 non-null    float64
 12  WACValue           290 non-null    float64
 13  CSM_QTY            2 non-null      float64
 14  CONSIGN_FINAL_QTY  290 non-null    float64
 15  POS_FINAL_QTY      290 non-null    float64
dtypes: datetime64[ns](1), float64(7), object(8)
memory usage: 38.5+ KB

,TRX_date,StoreCode,BillNo,ItemCode,ITEMLONGNAME,Quantity,DEPARTMENT,CLASS,SUBCLASS,UOM_CD,TotalAmt,NetValue,WACValue,CSM_QTY,CONSIGN_FINAL_QTY,POS_FINAL_QTY
0,2025-11-15,083,1C10830000011,101002005378,KINDER BUENO CHOCO T-2,3.0,001-CONFECTIONARY,02-001-CHOCOLATE,01-02-001-CHOCOLATE CANDY,PCS,54000.0,0.0,36300.0,NaN,0.0,3.0

In [6]:
print(df.BillNo.nunique())
print(df.ITEMLONGNAME.nunique())

47
48

In [ ]:
# Get top 10 most frequent products for this store
product_frequency = df.groupby('ITEMLONGNAME').size().sort_values(ascending=False)
top_products = product_frequency.head(10).index

store_df_filtered = df[df['ITEMLONGNAME'].isin(top_products)]

group_item = store_df_filtered.groupby('ITEMLONGNAME').size().sort_values(ascending=False) # calculate the appearance of the top 10 item for each transaction

group_item

ITEMLONGNAME
KINDER BUENO CHOCO T-2                          28
CHITATO LITE NORI SEAWEED 68GR                  19
BINTANG CRYSTAL CAN 320ML                       18
MUSHROOM ENOKI 100 GR                           18
GRAPE GREEN MUSCAT 500 GR                       16
CHITATO BEEF BBQ 68GR                           14
JERUK AFOURER                                   14
PEAR CENTURY                                    14
NANAS HONI SUNPRIDE MEDIUM 7S                   14
MUSHROOM CHAMPIGNON 250GR PACK                  11
GRAPE RED GLOBE RRC                             10
SUNCO OIL REFILL 2LT                             9
BEST WOK MIE GORENG ORIGINAL 85GR                8
HELLO PANDA STRAWBERRY 45GR                      8
HELLO PANDA COOKIES&CREAM 45GR                   8
APEL FUJI RRC                                    7
HELLO PANDA DOUBLE CHOCO 42GR                    6
HELLO PANDA CHOCO 45GR                           6
TOMATO CHERRY RED HYDROPONIC 250GR               5
SOSRO TEH BOTOL REGULER 450ML                    4
HELLO PANDA VANILA 45GR                          4
APEL FUJI BLUSH PREMIUM                          4
BEBE URUTAN BABI ASAP 500 GR                     4
CHERRIES                                         4
SUNPRIDE PISANG CAVENDISH                        3
COCONUT COCO THUMB PCS                           3
BEST WOK MI GORENG KOREAN XTRA HOT 73GR          3
COCONUT CLUSTERS GRANOLA CHOCOLATE MIX 100GR     2
BUNCIS KG                                        2
APEL ROCKIT PACK                                 2
FUKUMI RICE BOX 280GR                            2
SUNKIST NAVEL                                    2
COUNTRY CHOICE JUICE MANGO 1LT                   2
RASPBERRY ALL SEASON 170GR PACK                  2
AROMA CHICKEN COCKTAIL SSG 250GR                 1
PAN CASTILLO DE MAGNIA VINO TINTO 750ML          1
PAN CASTILLO DE MAGNIA VINI BLANCO 750ML         1
GOFRESS LITE MANGO BREEZE 24S                    1
HARIBO WORM 160GR                                1
MISTER POTATO ORIGINAL 106GR                     1
MALIA CHICKEN BREAKFAST SSG 250GR                1
KOL PUTIH BULAT KG                               1
COCONUT CLUSTERS GRANOLA ORIGINAL MIX 100GR      1
KENTANG BESAR KG                                 1
DELIMA IMPORT/POMEGRANATE                        1
DETTOL SHOWERFOAM COOL REF 370ML                 1
GENTLEGEN PARISIENNE GARDEN 700ML                1
VANISH CAIR  REF 425ML                           1
dtype: int64

In [8]:
transactions = store_df_filtered.groupby(['BillNo', 'ITEMLONGNAME'])['POS_FINAL_QTY'] \
                                .sum().unstack(fill_value=0)

transactions = transactions.apply(pd.to_numeric, errors='coerce').fillna(0)
transactions_binary = transactions.gt(0)  # Convert to boolean (True/False)

transactions_binary.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 1C10830000002 to 1C10830000048
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   BINTANG CRYSTAL CAN 320ML       44 non-null     bool
 1   CHITATO BEEF BBQ 68GR           44 non-null     bool
 2   CHITATO LITE NORI SEAWEED 68GR  44 non-null     bool
 3   GRAPE GREEN MUSCAT 500 GR       44 non-null     bool
 4   JERUK AFOURER                   44 non-null     bool
 5   KINDER BUENO CHOCO T-2          44 non-null     bool
 6   MUSHROOM CHAMPIGNON 250GR PACK  44 non-null     bool
 7   MUSHROOM ENOKI 100 GR           44 non-null     bool
 8   NANAS HONI SUNPRIDE MEDIUM 7S   44 non-null     bool
 9   PEAR CENTURY                    44 non-null     bool
dtypes: bool(10)
memory usage: 792.0+ bytes

In [9]:
# new method to do transaction binary

transactions_test = df.groupby("BillNo")["ITEMLONGNAME"].apply(list).tolist()

te = TransactionEncoder()
te_ary = te.fit(transactions_test).transform(transactions_test, sparse=True)

transactions_binary_test = pd.DataFrame.sparse.from_spmatrix(
    te_ary,
    columns=te.columns_
).astype(pd.SparseDtype(bool, fill_value=False))
transactions_binary_test.info()
#print(transactions_binary_test.sparse.density)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   APEL FUJI BLUSH PREMIUM                       1 non-null      Sparse[bool, 0]
 1   APEL FUJI RRC                                 1 non-null      Sparse[bool, 0]
 2   APEL ROCKIT PACK                              1 non-null      Sparse[bool, 0]
 3   AROMA CHICKEN COCKTAIL SSG 250GR              1 non-null      Sparse[bool, 0]
 4   BEBE URUTAN BABI ASAP 500 GR                  1 non-null      Sparse[bool, 0]
 5   BEST WOK MI GORENG KOREAN XTRA HOT 73GR       1 non-null      Sparse[bool, 0]
 6   BEST WOK MIE GORENG ORIGINAL 85GR             1 non-null      Sparse[bool, 0]
 7   BINTANG CRYSTAL CAN 320ML                     1 non-null      Sparse[bool, 0]
 8   BUNCIS KG                                     1 non-null      Sparse[bool, 0]
 9   CHERRIES                                      1 non-null      Sparse[bool, 0]
 10  CHITATO BEEF BBQ 68GR                         1 non-null      Sparse[bool, 0]
 11  CHITATO LITE NORI SEAWEED 68GR                1 non-null      Sparse[bool, 0]
 12  COCONUT CLUSTERS GRANOLA CHOCOLATE MIX 100GR  1 non-null      Sparse[bool, 0]
 13  COCONUT CLUSTERS GRANOLA ORIGINAL MIX 100GR   1 non-null      Sparse[bool, 0]
 14  COCONUT COCO THUMB PCS                        1 non-null      Sparse[bool, 0]
 15  COUNTRY CHOICE JUICE MANGO 1LT                1 non-null      Sparse[bool, 0]
 16  DELIMA IMPORT/POMEGRANATE                     1 non-null      Sparse[bool, 0]
 17  DETTOL SHOWERFOAM COOL REF 370ML              1 non-null      Sparse[bool, 0]
 18  FUKUMI RICE BOX 280GR                         1 non-null      Sparse[bool, 0]
 19  GENTLEGEN PARISIENNE GARDEN 700ML             1 non-null      Sparse[bool, 0]
 20  GOFRESS LITE MANGO BREEZE 24S                 1 non-null      Sparse[bool, 0]
 21  GRAPE GREEN MUSCAT 500 GR                     1 non-null      Sparse[bool, 0]
 22  GRAPE RED GLOBE RRC                           1 non-null      Sparse[bool, 0]
 23  HARIBO WORM 160GR                             1 non-null      Sparse[bool, 0]
 24  HELLO PANDA CHOCO 45GR                        1 non-null      Sparse[bool, 0]
 25  HELLO PANDA COOKIES&CREAM 45GR                1 non-null      Sparse[bool, 0]
 26  HELLO PANDA DOUBLE CHOCO 42GR                 1 non-null      Sparse[bool, 0]
 27  HELLO PANDA STRAWBERRY 45GR                   1 non-null      Sparse[bool, 0]
 28  HELLO PANDA VANILA 45GR                       1 non-null      Sparse[bool, 0]
 29  JERUK AFOURER                                 1 non-null      Sparse[bool, 0]
 30  KENTANG BESAR KG                              1 non-null      Sparse[bool, 0]
 31  KINDER BUENO CHOCO T-2                        1 non-null      Sparse[bool, 0]
 32  KOL PUTIH BULAT KG                            1 non-null      Sparse[bool, 0]
 33  MALIA CHICKEN BREAKFAST SSG 250GR             1 non-null      Sparse[bool, 0]
 34  MISTER POTATO ORIGINAL 106GR                  1 non-null      Sparse[bool, 0]
 35  MUSHROOM CHAMPIGNON 250GR PACK                1 non-null      Sparse[bool, 0]
 36  MUSHROOM ENOKI 100 GR                         1 non-null      Sparse[bool, 0]
 37  NANAS HONI SUNPRIDE MEDIUM 7S                 1 non-null      Sparse[bool, 0]
 38  PAN CASTILLO DE MAGNIA VINI BLANCO 750ML      1 non-null      Sparse[bool, 0]
 39  PAN CASTILLO DE MAGNIA VINO TINTO 750ML       1 non-null      Sparse[bool, 0]
 40  PEAR CENTURY                                  1 non-null      Sparse[bool, 0]
 41  RASPBERRY ALL SEASON 170GR PACK               1 non-null      Sparse[bool, 0]
 42  SOSRO TEH BOTOL REGULER 450ML                 1 non-null      Sparse[bool, 0]
 43  SUNCO OIL REFILL 2LT                          1 non-null      Sparse[bool, 0]
 44  SUNKIST NAVEL                                 1 non-null      Sparse[bool, 0]
 45  SUNPRIDE PISANG CAVENDISH                     1 non-null      Sparse[bool, 0]
 46  TOMATO CHERRY RED HYDROPONIC 250GR            1 non-null      Sparse[bool, 0]
 47  VANISH CAIR  REF 425ML                        1 non-null      Sparse[bool, 0]
dtypes: Sparse[bool, 0](48)
memory usage: 1.3 KB

C:\Users\Administrator\AppData\Local\Temp\ipykernel_16184\1397732912.py:8: FutureWarning: Allowing arbitrary scalar fill_value in SparseDtype is deprecated. In a future version, the fill_value must be a valid value for the SparseDtype.subtype.
  transactions_binary_test = pd.DataFrame.sparse.from_spmatrix(

In [10]:
transactions_binary_test.head(20)
#transactions_binary_test.to_csv('transactions_binary_test.csv', index=False)

,APEL FUJI BLUSH PREMIUM,APEL FUJI RRC,APEL ROCKIT PACK,AROMA CHICKEN COCKTAIL SSG 250GR,BEBE URUTAN BABI ASAP 500 GR,BEST WOK MI GORENG KOREAN XTRA HOT 73GR,BEST WOK MIE GORENG ORIGINAL 85GR,BINTANG CRYSTAL CAN 320ML,BUNCIS KG,CHERRIES,...,PAN CASTILLO DE MAGNIA VINI BLANCO 750ML,PAN CASTILLO DE MAGNIA VINO TINTO 750ML,PEAR CENTURY,RASPBERRY ALL SEASON 170GR PACK,SOSRO TEH BOTOL REGULER 450ML,SUNCO OIL REFILL 2LT,SUNKIST NAVEL,SUNPRIDE PISANG CAVENDISH,TOMATO CHERRY RED HYDROPONIC 250GR,VANISH CAIR REF 425ML
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,True,...,0,0,0,True,0,0,0,0,True,0
2,0,0,0,0,0,0,0,0,0,True,...,0,0,0,0,0,True,0,0,0,0
3,True,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,True,0,0,0,True
4,0,0,0,0,True,0,0,True,0,0,...,0,0,0,0,0,0,0,0,0,0
5,True,0,True,0,0,True,0,0,0,True,...,0,0,True,0,0,True,0,0,True,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,True,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,True,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,True,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,True,0,0,0,0,0
10,0,0,0,0,0,0,True,0,0,0,...,True,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,True,0,0,...,0,True,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,True,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,True,0,0,0,0
15,0,True,0,0,0,0,0,0,0,0,...,0,0,True,0,0,0,0,0,0,0
16,0,0,0,0,0,0,True,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,True,0,0,0,0,True,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,True,0,0,0,0,0,0,0,0,...,0,0,True,0,0,True,0,0,0,0

In [11]:
transactions_binary_test.head(100)

t10 = transactions_binary_test.head(10)

#convert to csv
t10.to_csv('t10_transactions_binary.csv', index=False)

t10

,APEL FUJI BLUSH PREMIUM,APEL FUJI RRC,APEL ROCKIT PACK,AROMA CHICKEN COCKTAIL SSG 250GR,BEBE URUTAN BABI ASAP 500 GR,BEST WOK MI GORENG KOREAN XTRA HOT 73GR,BEST WOK MIE GORENG ORIGINAL 85GR,BINTANG CRYSTAL CAN 320ML,BUNCIS KG,CHERRIES,...,PAN CASTILLO DE MAGNIA VINI BLANCO 750ML,PAN CASTILLO DE MAGNIA VINO TINTO 750ML,PEAR CENTURY,RASPBERRY ALL SEASON 170GR PACK,SOSRO TEH BOTOL REGULER 450ML,SUNCO OIL REFILL 2LT,SUNKIST NAVEL,SUNPRIDE PISANG CAVENDISH,TOMATO CHERRY RED HYDROPONIC 250GR,VANISH CAIR REF 425ML
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,True,...,0,0,0,True,0,0,0,0,True,0
2,0,0,0,0,0,0,0,0,0,True,...,0,0,0,0,0,True,0,0,0,0
3,True,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,True,0,0,0,True
4,0,0,0,0,True,0,0,True,0,0,...,0,0,0,0,0,0,0,0,0,0
5,True,0,True,0,0,True,0,0,0,True,...,0,0,True,0,0,True,0,0,True,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,True,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,True,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,True,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,True,0,0,0,0,0

Setelah membuat transaction binary dilajutkan dengan mencari support dari masing" item, Support adalah index kemunculun item dalam 1 periode transaksi/dataset (range value 0-1)

In [10]:
frequent_itemsets_test = fpgrowth(
    transactions_binary_test,
    min_support=0.001, # 0.001 = Only include itemsets appearing in ≥ 0.1% of transactions
    use_colnames=True,
    #max_len=2
)

frequent_itemsets_test.tail()

      support                                           itemsets
991  0.001150       (BCC HAM & CHEESE CROISSANT, BCC CAPPUCCINO)
992  0.001012  (BCC ALMOND CROISSANT, BCC MATCHA ALMOND CROIS...
993  0.001196  (BCC LEMON TART MERINGUE, BCC MIX FRUIT TARTLE...
994  0.001287                  (BCC CHOCOLATINE, BCC FLAT WHITE)
995  0.001196  (BCC CHOCOLATE WORDING, BCC CHOCOLATE CAKE WHOLE)

In [14]:
rules = association_rules(
    frequent_itemsets_test,
    metric="confidence",
    min_threshold=0.0 # 0.0 for no filter
)

print()
print(rules.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   antecedents         530 non-null    object
 1   consequents         530 non-null    object
 2   antecedent support  530 non-null    float64
 3   consequent support  530 non-null    float64
 4   support             530 non-null    float64
 5   confidence          530 non-null    float64
 6   lift                530 non-null    float64
 7   representativity    530 non-null    float64
 8   leverage            530 non-null    float64
 9   conviction          530 non-null    float64
 10  zhangs_metric       530 non-null    float64
 11  jaccard             530 non-null    float64
 12  certainty           530 non-null    float64
 13  kulczynski          530 non-null    float64
dtypes: float64(12), object(2)
memory usage: 58.1+ KB
None

In [ ]:
spark = SparkSession.builder.appName("FPGrowthExample").getOrCreate()
transactions = df.groupby("BillNo")["ItemCode"].apply(list).tolist()
df_spark = spark.createDataFrame([Row(items=items) for items in transactions])

fpGrowth = FPGrowth(itemsCol="items", minSupport=0.001, minConfidence=0.3)
model = fpGrowth.fit(df_spark)

# 5. Frequent itemsets
model.freqItemsets.show(truncate=False)

# 6. Association rules
model.associationRules.show(truncate=False)

# 7. Prediksi rekomendasi
model.transform(df_spark).show(truncate=False)

In [ ]:
#3
transactions = df.groupby("BillNo")["ItemCode"].apply(list).tolist()
n_transactions = len(transactions)

freqItemSet, rules_fpg = fpgrowth(transactions, minSupRatio=0.0, minConf=0.0)
transactions_sets = [set(t) for t in transactions]  # convert once, reuse

def calc_support(itemset):
    return sum(1 for t in transactions_sets if itemset.issubset(t)) / n_transactions

frequent_itemsets = pd.DataFrame([
    {"itemsets": frozenset(itemset), "support": calc_support(itemset)}
    for itemset in freqItemSet
])

# Ensure column dtypes
frequent_itemsets["itemsets"] = frequent_itemsets["itemsets"].apply(frozenset)
frequent_itemsets = frequent_itemsets.drop_duplicates(subset=["itemsets"]).reset_index(drop=True)

# --- Ensure subsets (fix for missing singletons) ---
existing = set(frequent_itemsets["itemsets"])
new_rows = []

for itemset in list(existing):
    if len(itemset) > 1:  # only expand if size >= 2
        for i in range(1, len(itemset)):
            for subset in combinations(itemset, i):
                subset_fs = frozenset(subset)
                if subset_fs not in existing:
                    new_rows.append({
                        "itemsets": subset_fs,
                        "support": calc_support(subset_fs)
                    })
                    existing.add(subset_fs)

if new_rows:
    frequent_itemsets = pd.concat(
        [frequent_itemsets, pd.DataFrame(new_rows)],
        ignore_index=True
    )
# -- END --

In [ ]:
rules = association_rules(
            frequent_itemsets, 
            metric="lift", 
            min_threshold=1.0 # lift, 1.0
        )

In [ ]:
# only 2 itemset with 2 item each pair, posible apriori rules = 4
# find the support for itemset and support for indivicual item in pairset

pair_set = [
        ['AQUA MINERAL WATER 1500ML', 'AQUA MINERAL WATER 600ML'],
        ['FRUIT CUT 30K', 'SUNPRIDE PISANG CAVENDISH'],
        ['AQUA MINERAL WATER 1500ML'], 
        ['AQUA MINERAL WATER 600ML'],
        ['FRUIT CUT 30K'],
        ['SUNPRIDE PISANG CAVENDISH'],
    ]

print(f"Transactions total: {len(t10)}")
print(f"Columns in binary: {t10.columns.nunique()} items")

def find_support(itemset):
    """Compute support of a given itemset from transactions binary df"""
    if all(col in t10.columns for col in itemset):
        count = t10[itemset].all(axis=1).sum()
        support = count / len(t10)
        return count, support
    else:
        return None, None

# loop through all sets
for pair in pair_set:
    count, support = find_support(pair)
    if count is not None:
        print(f"{pair}: support = {count} / {len(t10)} = {support:.6f}")
    else:
        print(f"❌ {pair} not found in transactions_binary.")

Transactions total: 10
Columns in binary: 10 items
['AQUA MINERAL WATER 1500ML', 'AQUA MINERAL WATER 600ML']: support = 1 / 10 = 0.100000
['FRUIT CUT 30K', 'SUNPRIDE PISANG CAVENDISH']: support = 1 / 10 = 0.100000
['AQUA MINERAL WATER 1500ML']: support = 1 / 10 = 0.100000
['AQUA MINERAL WATER 600ML']: support = 1 / 10 = 0.100000
['FRUIT CUT 30K']: support = 2 / 10 = 0.200000
['SUNPRIDE PISANG CAVENDISH']: support = 5 / 10 = 0.500000

In [ ]:
s_bill_data = (t10.index.tolist())
s_bill_data

['7C20020026848',
 '7C20020026851',
 '7C20020026855',
 '7C20020026872',
 '7C20020026875',
 '7C20020026883',
 '7C20020026886',
 '7C20020026888',
 '7C20020026894',
 '7C20020026896']

In [40]:
small_data = df[df["BillNo"].isin(s_bill_data)]
small_data = small_data.sort_values(by="BillNo", ascending=True).reset_index(drop=True)

print(small_data.columns)

Index(['TRX_date', 'StoreCode', 'BillNo', 'ItemCode', 'ITEMLONGNAME',
       'Quantity', 'DEPARTMENT', 'CLASS', 'SUBCLASS', 'UOM_CD', 'TotalAmt',
       'NetValue', 'WACValue', 'CSM_QTY', 'CONSIGN_FINAL_QTY',
       'POS_FINAL_QTY'],
      dtype='object')

In [41]:
small_data = small_data[
            ['TRX_date', 'BillNo', 'ItemCode', 'ITEMLONGNAME', 'Quantity','UOM_CD', 'TotalAmt',
            'NetValue', 'POS_FINAL_QTY']
        ]

small_data.to_csv('t10_trx_data.csv')
small_data

,TRX_date,BillNo,ItemCode,ITEMLONGNAME,Quantity,UOM_CD,TotalAmt,NetValue,POS_FINAL_QTY
0,2025-07-01,7C20020026848,101067012071,RTE SALAD BUFFET PEPITO,0.4280,KGS,64200.0,64200.0,0.4280
1,2025-07-01,7C20020026851,101012008984,DIAMOND FRESH MILK PLAIN 300ML,1.0000,PCS,12000.0,12000.0,1.0000
2,2025-07-01,7C20020026851,101024011683,SUNPRIDE PISANG CAVENDISH,0.4900,KGS,15925.0,15925.0,0.4900
3,2025-07-01,7C20020026851,101023011362,BABY ROMANA LETTUCE KG,0.1200,KGS,25800.0,25800.0,0.1200
4,2025-07-01,7C20020026851,101023011355,SELADA KERITING HIJAU KG,0.1019,KGS,14062.2,14062.0,0.1019
...,...,...,...,...,...,...,...,...,...
74,2025-07-01,7C20020026894,101009070566,EVIAN MINERAL WATER PET 500ML,4.0000,PCS,106000.0,106000.0,4.0000
75,2025-07-01,7C20020026896,101024011767,APEL FUJI WANG SHAN,1.5900,KGS,142305.0,142305.0,1.5900
76,2025-07-01,7C20020026896,101024011739,PEAR PACKAM,1.0200,KGS,54060.0,54060.0,1.0200
77,2025-07-01,7C20020026896,101024011793,JERUK HONEY MURCOT PREMIUM,1.1180,KGS,95589.0,95589.0,1.1180
78,2025-07-01,7C20020026896,101024011683,SUNPRIDE PISANG CAVENDISH,0.9620,KGS,31265.0,31265.0,0.9620