In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from sqlalchemy import create_engine, text
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
db_user = os.environ.get('dbwh_8555_user')
db_pass = os.environ.get('dbwh_8555_pass')

connection_string = f"mssql+pyodbc://{db_user}:{db_pass}@192.168.85.55/DBWH_8555?driver=ODBC+Driver+17+for+SQL+Server"
engine = create_engine(connection_string)

query = text(
    """
    SELECT 
        dd.[date] AS TRX_date,
        [StoreCode],
        [BillNo],
        [ItemCode],
        ITEMLONGNAME,
        [Quantity],
        DEPARTMENT,
        CLASS,
        SUBCLASS,
        [UOM_CD],
        [TotalAmt],
        [NetValue],
        [WACValue],
        [CSM_QTY],
        [CONSIGN_FINAL_QTY],
        [POS_FINAL_QTY]
    FROM [DBWH_8555].[dbo].[FactSalesTrxNew] fstn
    INNER JOIN dimdate dd ON dd.datekey = fstn.DateKey
    INNER JOIN DimItem di ON fstn.ItemCode = di.ITMCD
    WHERE dd.[date] BETWEEN :start_date AND :end_date AND StoreCode = '002'
    """)

In [3]:
with engine.connect() as conn:
    start_date = '2025-07-01'
    end_date = '2025-07-31'

    df = pd.read_sql(query, conn,  params={'start_date': start_date, 'end_date': end_date})
    
df = df[~df['ITEMLONGNAME'].str.contains('pepito bag', case=False, na=False)]
#df['month_year'] = pd.to_datetime(df['month_year'], format='%m-%Y')
#df['rule'] = df['antecedents'] + " → " + df['consequents']

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92626 entries, 0 to 95479
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TRX_date           92626 non-null  datetime64[ns]
 1   StoreCode          92626 non-null  object
 2   BillNo             92626 non-null  object
 3   ItemCode           92626 non-null  object
 4   ITEMLONGNAME       92626 non-null  object
 5   Quantity           92626 non-null  float64
 6   DEPARTMENT         92626 non-null  object
 7   CLASS              92626 non-null  object
 8   SUBCLASS           92626 non-null  object
 9   UOM_CD             92626 non-null  object
 10  TotalAmt           92626 non-null  float64
 11  NetValue           92626 non-null  float64
 12  WACValue           92626 non-null  float64
 13  CSM_QTY            4861 non-null   float64
 14  CONSIGN_FINAL_QTY  92626 non-null  float64
 15  POS_FINAL_QTY      92626 non-null  float64
dtypes: datetime64[ns](1), float64(7), object(8)
memory usage: 12.0+ MB

In [9]:
df.head(1)

,TRX_date,StoreCode,BillNo,ItemCode,ITEMLONGNAME,Quantity,DEPARTMENT,CLASS,SUBCLASS,UOM_CD,TotalAmt,NetValue,WACValue,CSM_QTY,CONSIGN_FINAL_QTY,POS_FINAL_QTY
0,2025-07-01,002,7C30020045747,101002000027,JUNGLEGOLD PEPPERMINT 100GR/70GR,1.0,001-CONFECTIONARY,02-001-CHOCOLATE,02-02-001-CHOCOLATE BLOCK,PCS,85500.0,85500.0,55006.933224,NaN,0.0,1.0

In [10]:
unique_bill_no = df.BillNo.nunique()
unique_item_no = df.ITEMLONGNAME.nunique()


print(unique_bill_no)
print(unique_item_no)

21748
9373

In [ ]:
# Get top 10 most frequent products for this store
product_frequency = df.groupby('ItemCode').size().sort_values(ascending=False)
top_products = product_frequency.head(10).index
bottom_products = product_frequency.tail(10).index

store_df_filtered = df[df['ItemCode'].isin(top_products)]

group_item = store_df_filtered.groupby('ItemCode').size().sort_values(ascending=False)

group_item

Index(['101022011275', '101022011286', '101022011287', '101005044327',
       '101005043844', '101022011319', '101022011321', '101002058737',
       '101005042404', '101011008918'],
      dtype='object', name='ItemCode')

In [12]:
transactions = store_df_filtered.groupby(['BillNo', 'ItemCode'])['POS_FINAL_QTY'] \
                                .sum().unstack(fill_value=0)

transactions = transactions.apply(pd.to_numeric, errors='coerce').fillna(0)
transactions_binary = transactions.gt(0)  # Convert to boolean (True/False)

transactions_binary.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6490 entries, 7C20020026848 to 7C50020032423
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   101009000754  6490 non-null   bool
 1   101009000755  6490 non-null   bool
 2   101016010907  6490 non-null   bool
 3   101024011683  6490 non-null   bool
 4   101024064912  6490 non-null   bool
 5   101026074480  6490 non-null   bool
 6   101067012071  6490 non-null   bool
 7   101091045414  6490 non-null   bool
 8   101091073120  6490 non-null   bool
 9   101091073156  6490 non-null   bool
dtypes: bool(10)
memory usage: 114.1+ KB

In [13]:
transactions_binary.head(100)

t10 = transactions_binary.head(10)

#convert to csv
transactions_binary.to_csv('transactions_binary.csv', index=False)

t10

ItemCode,101009000754,101009000755,101016010907,101024011683,101024064912,101026074480,101067012071,101091045414,101091073120,101091073156
BillNo,,,,,,,,,,
7C20020026848,False,False,False,False,False,False,True,False,False,False
7C20020026851,False,False,False,True,False,False,False,False,False,False
7C20020026855,False,False,False,True,False,False,False,False,False,False
7C20020026872,False,False,True,False,False,False,False,False,False,False
7C20020026875,False,False,False,True,False,False,False,False,False,False
7C20020026883,False,False,False,True,True,False,False,False,False,False
7C20020026886,False,False,False,False,False,True,False,False,False,False
7C20020026888,True,True,False,False,False,False,False,False,False,False
7C20020026894,False,False,False,False,True,False,False,False,False,False
7C20020026896,False,False,False,True,False,False,False,False,False,False

In [14]:
# Generate frequent itemsets
# pd.set_option('display.max_colwidth', None)
frequent_itemsets_test = apriori(
    t10,
    min_support=0.001, # 0.001 = Only include itemsets appearing in ≥ 0.1% of transactions
    use_colnames=True,
)

frequent_itemsets_test

   support                      itemsets
0      0.1                (101009000754)
1      0.1                (101009000755)
2      0.1                (101016010907)
3      0.5                (101024011683)
4      0.2                (101024064912)
5      0.1                (101026074480)
6      0.1                (101067012071)
7      0.1  (101009000754, 101009000755)
8      0.1  (101024011683, 101024064912)


### Support = (number of transactions containing the item) / (total number of transactions)

Total transaction of AQUA MINERAL WATER 1500ML is 1 = 1/10 = 0.1

Only get 2 itemsets, with 2 items each, possible apriori rules = 4

##### Confidence(A→B)= Support(A∪B)/Support(A)
Confidence asks:
“How often does B appear when A appears?”



-r1 = support(AQUA MINERAL WATER 600ML, AQUA MINERAL WATER 1500ML) / support(AQUA MINERAL WATER 600ML)
    = 0.1/0.1
    = 1

-r2 = support(AQUA MINERAL WATER 1500ML, AQUA MINERAL WATER 600ML) / support(AQUA MINERAL WATER 1500ML)
    = 0.1/0.1
    = 1

-r3 = support(FRUIT CUT 30K, SUNPRIDE PISANG CAVENDISH) / support(FRUIT CUT 30K)
    = 0.1/0.2
    = 0.5

-r4 = support(SUNPRIDE PISANG CAVENDISH, FRUIT CUT 30K) / support(SUNPRIDE PISANG CAVENDISH)
    = 0.1/0.5
    = 0.2


##### Lift(A→B)= Confidence(A→B)/Support(B)
Lift asks:
“How much more likely is B when A happens, compared to random chance of B?”

-r1 = confidence(AQUA MINERAL WATER 600ML, AQUA MINERAL WATER 1500ML) / support(AQUA MINERAL WATER 1500ML)
    = 1/0.1
    = 10

-r2 = confidence(AQUA MINERAL WATER 1500ML, AQUA MINERAL WATER 600ML) / support(AQUA MINERAL WATER 600ML)
    = 1/0.1
    = 10

-r3 = confidence(FRUIT CUT 30K, SUNPRIDE PISANG CAVENDISH) / support(SUNPRIDE PISANG CAVENDISH)
    = 0.5/0.5
    = 1

-r4 = confidence(SUNPRIDE PISANG CAVENDISH, FRUIT CUT 30K) / support(FRUIT CUT 30K)
    = 0.2/0.2
    = 1

In [15]:
rules_test = association_rules(frequent_itemsets_test, metric="confidence", min_threshold=0.1)
rules_test

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(101009000754),(101009000755),0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.000000,1.0,1.00
1,(101009000755),(101009000754),0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.000000,1.0,1.00
2,(101024011683),(101024064912),0.5,0.2,0.1,0.2,1.0,1.0,0.00,1.0,0.0,0.166667,0.0,0.35
3,(101024064912),(101024011683),0.2,0.5,0.1,0.5,1.0,1.0,0.00,1.0,0.0,0.166667,0.0,0.35

In [16]:
#total trx: 6490 
pd.set_option('display.max_colwidth', None)

frequent_itemsets = apriori(
    transactions_binary,
    min_support=0.001, # 0.001 = Only include itemsets appearing in ≥ 0.1% of transactions
    use_colnames=True,
)


rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.1)

code_to_name = dict(zip(df['ItemCode'], df['ITEMLONGNAME']))

def codes_to_names(codes):
    return ', '.join(code_to_name.get(code, code) for code in codes)

rules['antecedents_names'] = rules['antecedents'].apply(codes_to_names)
rules['consequents_names'] = rules['consequents'].apply(codes_to_names)

rules = rules [['antecedents', 'antecedents_names','consequents',
       'consequents_names', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift',
       'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski']]


rules['antecedents'] = rules['antecedents'].apply (lambda x: ', '.join(list(x)))
rules['consequents'] = rules['consequents'].apply (lambda x: ', '.join(list(x)))

rules.to_csv('product_associations.csv', index=False)



#frequent_itemsets.itemsets = frequent_itemsets.itemsets.apply (lambda x: ', '.join(list(x)))



rules_sort = rules.sort_values(by='confidence', ascending=False) 
#rules_filter = rules_sort[rules_sort['consequents'].str.contains('RTE SALAD BUFFET PEPITO', case=False, na=False)]

rules_sort
#frequent_itemsets

,antecedents,antecedents_names,consequents,consequents_names,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
7,"101009000754, 101026074480","AQUA MINERAL WATER 600ML, RTE-P CHICKEN YAKITORI",101067012071,RTE SALAD BUFFET PEPITO,0.004006,0.300924,0.002003,0.500000,1.661546,1.0,0.000798,1.398151,0.399752,0.006612,0.284770,0.253328
10,"101024064912, 101026074480","FRUIT CUT 30K, RTE-P CHICKEN YAKITORI",101067012071,RTE SALAD BUFFET PEPITO,0.006626,0.300924,0.002928,0.441860,1.468343,1.0,0.000934,1.252510,0.321088,0.009611,0.201603,0.225795
8,"101024011683, 101026074480","SUNPRIDE PISANG CAVENDISH, RTE-P CHICKEN YAKITORI",101067012071,RTE SALAD BUFFET PEPITO,0.003698,0.300924,0.001387,0.375000,1.246160,1.0,0.000274,1.118521,0.198268,0.004573,0.105962,0.189804
5,101026074480,RTE-P CHICKEN YAKITORI,101067012071,RTE SALAD BUFFET PEPITO,0.097997,0.300924,0.036210,0.369497,1.227872,1.0,0.006720,1.108758,0.205745,0.099830,0.098090,0.244912
9,"101067012071, 101024064912","RTE SALAD BUFFET PEPITO, FRUIT CUT 30K",101026074480,RTE-P CHICKEN YAKITORI,0.012789,0.097997,0.002928,0.228916,2.335948,1.0,0.001674,1.169785,0.579317,0.027143,0.145142,0.129395
6,"101067012071, 101009000754","RTE SALAD BUFFET PEPITO, AQUA MINERAL WATER 600ML",101026074480,RTE-P CHICKEN YAKITORI,0.010478,0.097997,0.002003,0.191176,1.950842,1.0,0.000976,1.115204,0.492562,0.018813,0.103303,0.105808
2,101024064912,FRUIT CUT 30K,101024011683,SUNPRIDE PISANG CAVENDISH,0.108012,0.212789,0.017103,0.158345,0.744142,1.0,-0.005881,0.935314,-0.278220,0.056317,-0.069160,0.119361
0,101009000754,AQUA MINERAL WATER 600ML,101067012071,RTE SALAD BUFFET PEPITO,0.083359,0.300924,0.010478,0.125693,0.417690,1.0,-0.014607,0.799577,-0.603316,0.028030,-0.250662,0.080256
4,101067012071,RTE SALAD BUFFET PEPITO,101026074480,RTE-P CHICKEN YAKITORI,0.300924,0.097997,0.036210,0.120328,1.227872,1.0,0.006720,1.025385,0.265469,0.099830,0.024757,0.244912
3,101024064912,FRUIT CUT 30K,101067012071,RTE SALAD BUFFET PEPITO,0.108012,0.300924,0.012789,0.118402,0.393462,1.0,-0.019715,0.792964,-0.633459,0.032283,-0.261091,0.080451
1,101016010907,CHICKEN BREAST BONELESS KG,101024011683,SUNPRIDE PISANG CAVENDISH,0.070878,0.212789,0.007396,0.104348,0.490382,1.0,-0.007686,0.878925,-0.527969,0.026771,-0.137753,0.069553

In [17]:
print(rules.columns)

'''

antecedents', 'consequents', 'antecedent support', 'consequent support', 'support', 'confidence', 'lift', 
'representativity', 'leverage', 'conviction', 'zhangs_metric','jaccard', 'certainty', 'kulczynski', 'store_code', 'month_year'

'''

Index(['antecedents', 'antecedents_names', 'consequents', 'consequents_names',
       'antecedent support', 'consequent support', 'support', 'confidence',
       'lift', 'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski'],
      dtype='object')

"\n\nantecedents', 'consequents', 'antecedent support', 'consequent support', 'support', 'confidence', 'lift', \n'representativity', 'leverage', 'conviction', 'zhangs_metric','jaccard', 'certainty', 'kulczynski', 'store_code', 'month_year'\n\n"

In [18]:
pair = ['CHICKEN BREAST BONELESS KG', 'BROKOLI LOKAL KG', 'SUNPRIDE PISANG CAVENDISH', 'DRAGON FRUIT MERAH', 'WORTEL MEDAN KG']

# convert item code to item name
transactions_with_names = transactions_binary.rename(columns=code_to_name)

transactions_with_names.to_csv('transactions_with_names.csv')


# Check dimensions
print(f"Transactions total: {len(transactions_with_names)}")
print(f"Columns in binary: {transactions_with_names.columns.nunique()} items")

# Check how many transactions contain both items
if all(col in transactions_with_names.columns for col in pair):
    count = transactions_with_names[pair].all(axis=1).sum()
    support = count / len(transactions_with_names)
    print(f"Support from binary: {count} / {len(transactions_with_names)} = {support:.6f}")
else:
    print("❌ One or both item names not found in transactions_binary.")

Transactions total: 6490
Columns in binary: 10 items
❌ One or both item names not found in transactions_binary.

In [14]:
# Re-run Apriori
frequent_itemsets = apriori(
    transactions_with_names,
    min_support=0.001,
    use_colnames=True
)

# Filter for the pair
mask = frequent_itemsets['itemsets'].apply(lambda x: x == frozenset(pair))
print(frequent_itemsets[mask])

      support  \
222  0.001028

                                                                                          itemsets
222  (DRAGON FRUIT MERAH, SUNPRIDE PISANG CAVENDISH, CHICKEN BREAST BONELESS KG, BROKOLI LOKAL KG)